// <auto-generated />
using System;
using FMDDS.Data.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260705181114_MakePatientFieldsNullable")]
    partial class MakePatientFieldsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FMDDS.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditLogID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("AuditLogID");

                    b.HasIndex("UserID");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.Case", b =>
                {
                    b.Property<int>("CaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CaseID"));

                    b.Property<int?>("AssignedOfficerID")
                        .HasColumnType("integer");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("HospitalID")
                        .HasColumnType("integer");

                    b.Property<int>("PatientID")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferralSourceTypeID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("WardID")
                        .HasColumnType("integer");

                    b.HasKey("CaseID");

                    b.HasIndex("AssignedOfficerID");

                    b.HasIndex("CaseNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Case_CaseNumber");

                    b.HasIndex("HospitalID");

                    b.HasIndex("PatientID");

                    b.HasIndex("ReferralSourceTypeID");

                    b.HasIndex("WardID");

                    b.ToTable("Case", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.ChainOfCustody", b =>
                {
                    b.Property<int>("CustodyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustodyID"));

                    b.Property<int>("EvidenceID")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReasonForTransfer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReceivingOfficerID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransferTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TransferringOfficerID")
                        .HasColumnType("integer");

                    b.HasKey("CustodyID");

                    b.HasIndex("EvidenceID");

                    b.HasIndex("ReceivingOfficerID");

                    b.HasIndex("TransferringOfficerID");

                    b.ToTable("ChainOfCustody", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.ClinicalExamination", b =>
                {
                    b.Property<int>("ClinicalExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClinicalExamID"));

                    b.Property<int>("CaseID")
                        .HasColumnType("integer");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExaminerID")
                        .HasColumnType("integer");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClinicalExamID");

                    b.HasIndex("CaseID");

                    b.HasIndex("ExaminerID");

                    b.ToTable("ClinicalExamination", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.Evidence", b =>
                {
                    b.Property<int>("EvidenceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EvidenceID"));

                    b.Property<int>("CaseID")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EvidenceID");

                    b.HasIndex("CaseID");

                    b.ToTable("Evidence", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.Hospital", b =>
                {
                    b.Property<int>("HospitalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HospitalID"));

                    b.Property<string>("HospitalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HospitalID");

                    b.ToTable("Hospital", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.LaboratoryRequest", b =>
                {
                    b.Property<int>("LabRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabRequestID"));

                    b.Property<int>("CaseID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LabRequestID");

                    b.HasIndex("CaseID");

                    b.ToTable("LaboratoryRequest", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.LaboratoryResult", b =>
                {
                    b.Property<int>("LabResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabResultID"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LabRequestID")
                        .HasColumnType("integer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LabResultID");

                    b.HasIndex("LabRequestID")
                        .IsUnique();

                    b.ToTable("LaboratoryResult", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.MedicoLegalReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ApprovedByID")
                        .HasColumnType("integer");

                    b.Property<int>("CaseID")
                        .HasColumnType("integer");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReportID");

                    b.HasIndex("ApprovedByID");

                    b.HasIndex("CaseID");

                    b.ToTable("MedicoLegalReport", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NIC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.HasKey("PatientID");

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.PostmortemExamination", b =>
                {
                    b.Property<int>("PostmortemExamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PostmortemExamID"));

                    b.Property<int>("CaseID")
                        .HasColumnType("integer");

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExaminerID")
                        .HasColumnType("integer");

                    b.Property<string>("Findings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PostmortemExamID");

                    b.HasIndex("CaseID");

                    b.HasIndex("ExaminerID");

                    b.ToTable("PostmortemExamination", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.ReferralSourceType", b =>
                {
                    b.Property<int>("ReferralSourceTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReferralSourceTypeID"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReferralSourceTypeID");

                    b.ToTable("ReferralSourceTypes");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.Ward", b =>
                {
                    b.Property<int>("WardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WardID"));

                    b.Property<int>("HospitalID")
                        .HasColumnType("integer");

                    b.Property<string>("WardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WardID");

                    b.HasIndex("HospitalID");

                    b.ToTable("Ward", (string)null);
                });

            modelBuilder.Entity("FMDDS.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.Case", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.User", "AssignedOfficer")
                        .WithMany()
                        .HasForeignKey("AssignedOfficerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FMDDS.Data.Entities.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FMDDS.Data.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMDDS.Data.Entities.ReferralSourceType", "ReferralSourceType")
                        .WithMany()
                        .HasForeignKey("ReferralSourceTypeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FMDDS.Data.Entities.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WardID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AssignedOfficer");

                    b.Navigation("Hospital");

                    b.Navigation("Patient");

                    b.Navigation("ReferralSourceType");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.ChainOfCustody", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.Evidence", "Evidence")
                        .WithMany()
                        .HasForeignKey("EvidenceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMDDS.Data.Entities.User", "ReceivingOfficer")
                        .WithMany()
                        .HasForeignKey("ReceivingOfficerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FMDDS.Data.Entities.User", "TransferringOfficer")
                        .WithMany()
                        .HasForeignKey("TransferringOfficerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evidence");

                    b.Navigation("ReceivingOfficer");

                    b.Navigation("TransferringOfficer");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.ClinicalExamination", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMDDS.Data.Entities.User", "Examiner")
                        .WithMany()
                        .HasForeignKey("ExaminerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Examiner");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.Evidence", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.LaboratoryRequest", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.LaboratoryResult", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.LaboratoryRequest", "LabRequest")
                        .WithOne("Result")
                        .HasForeignKey("FMDDS.Data.Entities.LaboratoryResult", "LabRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LabRequest");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.MedicoLegalReport", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByID");

                    b.HasOne("FMDDS.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.PostmortemExamination", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FMDDS.Data.Entities.User", "Examiner")
                        .WithMany()
                        .HasForeignKey("ExaminerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Examiner");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.Ward", b =>
                {
                    b.HasOne("FMDDS.Data.Entities.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("FMDDS.Data.Entities.LaboratoryRequest", b =>
                {
                    b.Navigation("Result")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
